### ISSUE TITLE
Discrepancies in semantic types of CUI/mentions

### ISSUE THREAD

**Issue by ajaynagesh** [chanzuckerberg/MedMentions#1]
Hi, 

I see some discrepancies in labels in some of the data points: 

1) Some entities have only one type: 
For e.g.: When I search for C0854135 (Pseudomonas aeruginosa infection) on UMLS (2017AA), I get the type as T047 [disease or Syndrome]. But I see that it has been marked with T038 [biologic function]. Now this CUI has only one type, so there is no question of least common ancestor. Could you please clarify.

![screen shot 2018-09-14 at 7 29 34 pm](https://user-images.githubusercontent.com/5205671/45581608-14c5b680-b856-11e8-9a73-9bdaac79d5a6.png)

2) Also in some cases, I do not see any type or a different type when I search in UMLS (2017AA) For e.g.: C0444245 (Deoxyribonucleic acid sample) has type T026 [cell component] in UMLS but is marked as T017 [Anatomical Structure] 

![screen shot 2018-09-14 at 7 48 57 pm](https://user-images.githubusercontent.com/5205671/45581701-c9aca300-b857-11e8-9c3e-4d7d270c6cf9.png)

3) In some cases, mentions are marked with UnknownType, but they do have a semantic type in UMLS (2017AA). For e.g.: C0563034 ( Aquatic environment) in UMLS has T067 [Phenomenon or Process]

![screen shot 2018-09-14 at 7 57 18 pm](https://user-images.githubusercontent.com/5205671/45581745-6e2ee500-b858-11e8-8799-94377c832cc9.png)

**Comment by czi-sunil** [comment]
Ajay, thanks for catching this issue. The data (and description and stats) have been corrected. The format is the same as before, with the following exception: when mentions are annotated with concepts linked to multiple semantic types, the type field has a comma-separated list of all these types. There is an example in the main README.md file.
