### ISSUE TITLE
Some entities are empty

### ISSUE THREAD

**Issue by ajaynagesh** [chanzuckerberg/MedMentions#2]
In the newly updated dataset, I saw some entities which are empty and have zero spans. For instance, in line `186449` of `corpus_pubtator.txt` I see the following line: 

`27909876        549     549             T070    C1456803`

empty span from 549 to 549 

Further I checked there are 98 of those lines: 

`➜  data git:(master) ✗ grep -v -e '|t|' -e '|a|' -e ^$  corpus_pubtator.txt | cut -f4 | grep ^$ | wc -l` 
`98`

**Comment by czi-sunil** [comment]
Thanks for the report, Ajay. We are looking into this.

**Comment by czi-sunil** [comment]
After review, we decided to remove all mentions with an empty text span from the corpus. Files have been updated.

**Comment by ajaynagesh** [comment]
great, thanks, @czi-sunil!
