### ISSUE TITLE
Different MedMentions datasets

### ISSUE THREAD

**Issue by izuna385** [chanzuckerberg/MedMentions#3]
Thanks for opening dataset's repository. I'm much interested in this dataset.

In [Murty's paper](https://aclweb.org/anthology/P18-1010), there is a statistics about dataset, which I cite here.

![image](https://user-images.githubusercontent.com/35322641/60512769-789b6c00-9d10-11e9-84f9-f5fad500edc8.png)

But this statistics is different from AKBC'19 paper.
(For example, in AKBC'19 paper, total abstracts are 4,392, but in Murty's one sum is 3704.)

I'd appreciate it if you could let me know where this difference came from.
Thanks.

**Comment by czi-sunil** [comment]
The dataset in this repository is the official MedMentions dataset. I believe Murty used a subset of this data.
