### ISSUE TITLE
Bad annotations ?

### ISSUE THREAD

**Issue by helboukkouri** [chanzuckerberg/MedMentions#6]
Hi,

I wrote a simple code to check whether the shown mention's text matches the given character spans and found some wrong matches. I hope this isn't an issue with my code and that you can confirm if these are indeed bad annotations : [bad_annotations.txt](https://github.com/chanzuckerberg/MedMentions/files/4220392/bad_annotations.txt)

**Comment by Syncrossus** [comment]
Are you sure you're handling the index increase between title and abstract properly? IIRC, if the last character of the title is character `n`, then the first character of the abstract is numbered `n + 2`.

**Comment by helboukkouri** [comment]
> Are you sure you're handling the index increase between title and abstract properly? IIRC, if the last character of the title is character `n`, then the first character of the abstract is numbered `n + 2`.

I simply join both using a space character then use the given character spans to retrieve the entities. I don't have any problem matching all the other entities, but those I linked in the text actually don't appear in the text at all. It seems like parts of some texts (abstracts) is missing.

I am using the ST21PV dataset.

**Comment by czi-sunil** [comment]
I was not able to reproduce this problem.

**Comment by GregSilverman** [comment]
Hi,
I am actually getting a very large number of discrepancies between the manual annotations and the text (viz., the title + abstract). I am doing as suggested by using `n+2` for the first char of the abstract, along with just trying a space, etc. 

The discrepancies are inconsistent across all 4k documents, too.

**Comment by czi-sunil** [comment]
Using the following code:
```
def check_mentions(pbttr_file: str):

    docid = None
    title = None
    abstr = None
    doc = None

    n_docs = 0
    n_men = 0
    n_err_pmid = 0
    n_err_men = 0

    with open(pbttr_file) as f:
        ln = 0
        for line in f:
            ln += 1
            line = line.strip()
            if not line:
                docid = None
                title = None
                abstr = None
                doc = None
            elif "\t" not in line:
                pmid, label, txt = line.split("|", maxsplit=2)
                if docid != pmid:
                    docid = pmid
                    n_docs += 1

                if label == "t":
                    title = txt
                else:
                    abstr = txt
            else:
                n_men += 1

                if doc is None:
                    doc = title + "\n" + ("" if not abstr else abstr)

                pmid, ch_s, ch_e, mention, tid, cuid = line.split("\t")

                if pmid != docid:
                    n_err_pmid += 1
                    print(f"Err at line {ln}: PMID mismatch")

                ch_s, ch_e = int(ch_s), int(ch_e)

                if mention != doc[ch_s:ch_e]:
                    n_err_men += 1
                    print(f"Err at line {ln}: Mention doesn't match text at {ch_s}:{ch_e} = {doc[ch_s : ch_e]}")

    print("Nbr docs     = {:7,d}".format(n_docs))
    print("Nbr mentions = {:7,d}".format(n_men))
    print("Nbr PMID mismatch errs    =", n_err_pmid)
    print("Nbr Mention mismatch errs =", n_err_men)
    return
```

Running in ipython:

```
In [1]: from medmentions import check_mentions                                                                                              

In [2]: check_mentions("MedMentions/full/data/corpus_pubtator.txt")                                                          
Nbr docs     =   4,392
Nbr mentions = 352,496
Nbr PMID mismatch errs    = 0
Nbr Mention mismatch errs = 0
```

**Comment by GregSilverman** [comment]
Thanks! This helps significantly (you might wish to put this in the README).
